# LABPRACTICE
print("the sky is blue")
print("My favoriet color is baby blue, lavender, and yellow")
print("Yes the grass is green and the sky is blue and the sun is yellow.")
print("My favorite season is fall")
print("I am 16 and  I like  Coffee and strawberry milkshakes")
print("I like to write poems and doodle")
print("Life is great")
print("This class was challenging")
print("I like to watch  Netflix ")
print("python ./Labpractice.py")